RAW = """
QB|Joe Burrow=LSU|Tim Tebow=Florida|Cam Newton=Auburn|Baker Mayfield=Oklahoma|Marcus Mariota=Oregon|Bryce Young=Alabama|Kyler Murray=Oklahoma|Jameis Winston=Florida State|Caleb Williams=USC|Jayden Daniels=LSU|Vince Young=Texas|Matt Leinart=USC|Carson Palmer=USC|Troy Smith=Ohio State|Sam Bradford=Oklahoma|Doug Flutie=Boston College|Danny Wuerffel=Florida|Johnny Manziel=Texas A&M|Chris Weinke=Florida State|Charlie Ward=Florida State|Andre Ware=Houston|Vinny Testaverde=Miami (FL)|Ty Detmer=BYU|Eric Crouch=Nebraska|Peyton Manning=Tennessee|Trevor Lawrence=Clemson|Deshaun Watson=Clemson|Justin Fields=Ohio State|C.J. Stroud=Ohio State|Bo Nix=Oregon|Shedeur Sanders=Colorado|Drew Brees=Purdue|Philip Rivers=NC State|Matt Ryan=Boston College|Andrew Luck=Stanford|Russell Wilson=Wisconsin|Jim Kelly=Miami (FL)|Bernie Kosar=Miami (FL)|Steve Young=BYU|Jim McMahon=BYU|Rick Mirer=Notre Dame|Brady Quinn=Notre Dame|Colt McCoy=Texas|Case Keenum=Houston|Graham Harrell=Texas Tech|Colt Brennan=Hawai'i|Denard Robinson=Michigan|Tim Couch=Kentucky
RB|Barry Sanders=Oklahoma State|Archie Griffin=Ohio State|Earl Campbell=Texas|Reggie Bush=USC|Derrick Henry=Alabama|Mark Ingram=Alabama|Bo Jackson=Auburn|Tony Dorsett=Pittsburgh|Marcus Allen=USC|Saquon Barkley=Penn State|Christian McCaffrey=Stanford|Adrian Peterson=Oklahoma|Herschel Walker=Georgia|Charles White=USC|Eddie George=Ohio State|Ron Dayne=Wisconsin|Leonard Fournette=LSU|Melvin Gordon=Wisconsin|Ricky Williams=Texas|George Rogers=South Carolina|Mike Rozier=Nebraska|Billy Sims=Oklahoma|Rashaan Salaam=Colorado|Ezekiel Elliott=Ohio State|O.J. Simpson=USC|Jim Brown=Syracuse|Gale Sayers=Kansas|Emmitt Smith=Florida|Jonathan Taylor=Wisconsin|Todd Gurley=Georgia|Nick Chubb=Georgia|Trent Richardson=Alabama|Darren McFadden=Arkansas|LaDainian Tomlinson=TCU|Marshawn Lynch=California|Le’Veon Bell=Michigan State|Shaun Alexander=Alabama|Cedric Benson=Texas|Corey Dillon=Washington|DeMarco Murray=Oklahoma|Jamaal Charles=Texas|Darren Sproles=Kansas State|Steven Jackson=Oregon State|Toby Gerhart=Stanford|Montee Ball=Wisconsin|Ki-Jana Carter=Penn State|Kevin Faulk=LSU|Napoleon Kaufman=Washington|Bijan Robinson=Texas
WR|Jerry Rice=Mississippi Valley State|Desmond Howard=Michigan|Johnny Rodgers=Nebraska|DeVonta Smith=Alabama|Tim Brown=Notre Dame|Calvin Johnson=Georgia Tech|Julio Jones=Alabama|Amari Cooper=Alabama|Larry Fitzgerald=Pittsburgh|Michael Irvin=Miami (FL)|Keyshawn Johnson=USC|Marvin Harrison=Syracuse|Randy Moss=Marshall|Braylon Edwards=Michigan|David Boston=Ohio State|Anthony Carter=Michigan|Jaylen Waddle=Alabama|Marqise Lee=USC|Ja’Marr Chase=LSU|Justin Jefferson=LSU|Marvin Harrison Jr.=Ohio State|CeeDee Lamb=Oklahoma|A.J. Green=Georgia|Odell Beckham Jr.=LSU|Stefon Diggs=Maryland|D.K. Metcalf=Ole Miss|Sammy Watkins=Clemson|JuJu Smith-Schuster=USC|Robert Woods=USC|Golden Tate=Notre Dame|Percy Harvin=Florida|Terry McLaurin=Ohio State|Koren Robinson=NC State|Santonio Holmes=Ohio State|Michael Floyd=Notre Dame|Josh Reed=LSU
OL|Orlando Pace=Ohio State|Anthony Munoz=USC|Bruce Matthews=USC|Tony Boselli=USC|Jonathan Ogden=UCLA|Randall McDaniel=Arizona State|Will Shields=Nebraska|Zach Wiegert=Nebraska|Chris Samuels=Alabama|Robert Gallery=Iowa|Jake Long=Michigan|Jammal Brown=Oklahoma|David DeCastro=Stanford|Alex Mack=California|Jim Parker=Ohio State|Steve Hutchinson=Michigan|Joe Thomas=Wisconsin|Taylor Lewan=Michigan|Andrew Whitworth=LSU|Trent Williams=Oklahoma|Laremy Tunsil=Ole Miss|Quenton Nelson=Notre Dame|Tyron Smith=USC|Penei Sewell=Oregon|Rashawn Slater=Northwestern|Lane Johnson=Oklahoma|Cam Robinson=Alabama|Mitchell Schwartz=California|Bill Fralic=Pittsburgh|Russ Grimm=Pittsburgh|Lomas Brown=Florida
EDGE|Bruce Smith=Virginia Tech|Reggie White=Tennessee|Derrick Thomas=Alabama|Myles Garrett=Texas A&M|Julius Peppers=North Carolina|Hugh Green=Pittsburgh|Nick Bosa=Ohio State|Chase Young=Ohio State|Ndamukong Suh=Nebraska|Dwight Freeney=Syracuse|Von Miller=Texas A&M|Jadeveon Clowney=South Carolina|Terrell Suggs=Arizona State|DeMarcus Ware=Troy|Mario Williams=NC State|Will Anderson Jr.=Alabama|Aidan Hutchinson=Michigan|Joey Bosa=Ohio State|Clay Matthews=USC|Elvis Dumervil=Louisville|Jason Pierre-Paul=South Florida|Cornelius Bennett=Alabama|Chris Doleman=Pittsburgh|Simeon Rice=Illinois|Peter Boulware=Florida State|Justin Tuck=Notre Dame
DB|Charles Woodson=Michigan|Jim Thorpe=Carlisle|Kyle Hamilton=Notre Dame|Champ Bailey=Georgia|Patrick Peterson=LSU|Jalen Ramsey=Florida State|Deion Sanders=Florida State|Sean Taylor=Miami (FL)|Eric Berry=Tennessee|Marshon Lattimore=Ohio State|Ed Reed=Miami (FL)|Tyrann Mathieu=LSU|Derwin James=Florida State|Ronnie Lott=USC|Rod Woodson=Purdue|Aeneas Williams=Southern|Minkah Fitzpatrick=Alabama|Derek Stingley Jr.=LSU|Sauce Gardner=Cincinnati|Xavier Rhodes=Florida State|Morris Claiborne=LSU|Antonio Cromartie=Florida State|Malcolm Jenkins=Ohio State|Leon Hall=Michigan|Bennie Blades=Miami (FL)|Budda Baker=Washington|Adoree’ Jackson=USC
LB|Dick Butkus=Illinois|Lawrence Taylor=North Carolina|Luke Kuechly=Boston College|Derrick Brooks=Florida State|Manti Teʻo=Notre Dame|Micah Parsons=Penn State|Brian Bosworth=Oklahoma|LaVar Arrington=Penn State|Bobby Wagner=Utah State|C.J. Mosley=Alabama|Dan Morgan=Miami (FL)|Roquan Smith=Georgia|Ray Lewis=Miami (FL)|Junior Seau=USC|Patrick Willis=Ole Miss|Chris Spielman=Ohio State|Zach Thomas=Texas Tech|Devin White=LSU|A.J. Hawk=Ohio State|James Laurinaitis=Ohio State|Sean Lee=Penn State|Jerod Mayo=Tennessee|Rey Maualuga=USC|Rolando McClain=Alabama|Reggie Ragland=Alabama|Devin Bush=Michigan|Nakobe Dean=Georgia|Keith Brooking=Georgia Tech
"""
SCHOOL = {}
for line in RAW.strip().splitlines():
    pos, rest = line.split('|', 1)
    for item in rest.split('|'):
        n, sc = item.rsplit('=', 1)
        SCHOOL[(pos, n)] = sc
